# Pulls base image
FROM ubuntu:20.04

# Installs Samba
RUN apt update
RUN apt install samba -y

# Sets Timezone
ENV TZ=America/Toronto

#Makes Data Directory
RUN mkdir /Data

# Create user for Samba
RUN adduser ryan 
RUN usermod -u 1000 ryan
RUN groupmod -g 1000 ryan

# Keeps Container from Dieing
ENTRYPOINT ["tail", "-f", "/dev/null"]